### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by gilbert-rehling** [eloquent/composer-config-reader#13]
It appears that this library relies on another:
https://github.com/justinrainbow/json-schema
After upgrading to PHP 7.4 the errro listed as the title is consistently reported, and disruptsnthe JSON responses for API's.
I realise the error is not a direct result of code in this library, but this is a heads-up that a library that is relied upon is causing issues.

**Comment by gilbert-rehling** [comment]
Upon further investigation, it seems that this library is referencing an outdated version of the justinrainbow/json-schema repo.
"require": {
        "php": ">=5.3",
        "eloquent/enumeration": "^5",
        "justinrainbow/json-schema": "^4"
    },

Their latest version is now: v5.2.10  and is compatible with PHP 7.4

Unfortunately I cannot simply require their library directly as composer complains of a version requirement conflict for your library.

**Comment by ezzatron** [comment]
Thanks. I'll do my best to get to this soon, but a PR is probably the best way to speed things along if you're able to help out 👍

**Comment by gilbert-rehling** [comment]
Sure thing.   I'll 'fake' the update on my Dev box tonight to ensure that there are no apparent issues tying your library to their version 5.* tree..

**Comment by ezzatron** [comment]
[3.0.0](https://github.com/eloquent/composer-config-reader/releases/tag/3.0.0) is now released which uses `json-schema@^5`. Note that it's still using the Composer 1 schema.

I'm going to look into how much the schema has changed for Composer 2. I may not be able to continue support for this library if the changes are extensive, so it may be worth considering removing your dependency on this library if possible. It's just fancy JSON parsing at the end of the day 🙃
